[package]
name = "Rust-Timeseries-Statistics"
version = "0.1.0"
edition = "2026"

[dependencies]
complot = "0.3.5"
csv = "1.4.0"
itertools = "0.14.0"
ndarray = "0.17.2"
rustfft = "6.4.1"
thiserror = "2.0.18"
